"""agregar tablas de partidas y duelos

Revision ID: a03d337e8997
Revises: 50ca309bd94c
Create Date: 2026-09-24 18:37:56.057943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03d337e8997'
down_revision: Union[str, None] = '50ca309bd94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('INDIVIDUAL', 'DUELO', name='tipo_partida_enum'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE_RIVAL', 'EN_CURSO', 'FINALIZADA', name='estado_partida_enum'), server_default='EN_CURSO', nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_id'), 'partidas', ['id'], unique=False)
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('opcion_a', sa.String(length=255), nullable=False),
    sa.Column('opcion_b', sa.String(length=255), nullable=False),
    sa.Column('opcion_c', sa.String(length=255), nullable=False),
    sa.Column('opcion_d', sa.String(length=255), nullable=False),
    sa.Column('respuesta_correcta', sa.String(length=1), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_categoria_id'), 'preguntas', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_preguntas_id'), 'preguntas', ['id'], unique=False)
    op.create_table('partidas_duelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=False),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('nombre_invitado', sa.String(length=100), nullable=True),
    sa.Column('puntaje_jugador1', sa.Integer(), server_default='0', nullable=False),
    sa.Column('puntaje_jugador2', sa.Integer(), server_default='0', nullable=False),
    sa.Column('numero_ganador', sa.Integer(), nullable=True),
    sa.Column('fecha_emparejamiento', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_duelo_jugador1_id'), 'partidas_duelo', ['jugador1_id'], unique=False)
    op.create_index(op.f('ix_partidas_duelo_jugador2_id'), 'partidas_duelo', ['jugador2_id'], unique=False)
    op.create_table('partidas_individuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_final', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_individuales_jugador_id'), 'partidas_individuales', ['jugador_id'], unique=False)
    op.create_table('preguntas_partida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('numero_jugador', sa.Integer(), server_default='1', nullable=False),
    sa.Column('opcion_seleccionada', sa.String(length=1), nullable=True),
    sa.Column('es_correcta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('esta_respondida', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tiempo_respuesta_segundos', sa.Integer(), nullable=True),
    sa.Column('puntaje_obtenido', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_mostrada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partida_id', 'numero_jugador', 'orden', name='uq_pregunta_partida_orden')
    )
    op.create_index(op.f('ix_preguntas_partida_id'), 'preguntas_partida', ['id'], unique=False)
    op.create_index(op.f('ix_preguntas_partida_partida_id'), 'preguntas_partida', ['partida_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preguntas_partida_partida_id'), table_name='preguntas_partida')
    op.drop_index(op.f('ix_preguntas_partida_id'), table_name='preguntas_partida')
    op.drop_table('preguntas_partida')
    op.drop_index(op.f('ix_partidas_individuales_jugador_id'), table_name='partidas_individuales')
    op.drop_table('partidas_individuales')
    op.drop_index(op.f('ix_partidas_duelo_jugador2_id'), table_name='partidas_duelo')
    op.drop_index(op.f('ix_partidas_duelo_jugador1_id'), table_name='partidas_duelo')
    op.drop_table('partidas_duelo')
    op.drop_index(op.f('ix_preguntas_id'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_categoria_id'), table_name='preguntas')
    op.drop_table('preguntas')
    op.drop_index(op.f('ix_partidas_id'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###

