"""cambiar es_correcta y esta_respondida a boolean

Revision ID: 1e42ce65396a
Revises: a03d337e8997
Create Date: 2026-09-24 20:48:12.514481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e42ce65396a'
down_revision: Union[str, None] = 'a03d337e8997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preguntas_partida', 'es_correcta', server_default=None)
    op.alter_column(
        'preguntas_partida', 'es_correcta',
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
        postgresql_using='es_correcta::boolean',
    )
    op.alter_column('preguntas_partida', 'es_correcta', server_default=sa.text('false'))

    op.alter_column('preguntas_partida', 'esta_respondida', server_default=None)
    op.alter_column(
        'preguntas_partida', 'esta_respondida',
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        existing_nullable=False,
        postgresql_using='esta_respondida::boolean',
    )
    op.alter_column('preguntas_partida', 'esta_respondida', server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preguntas_partida', 'esta_respondida', server_default=None)
    op.alter_column(
        'preguntas_partida', 'esta_respondida',
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using='esta_respondida::integer',
    )
    op.alter_column('preguntas_partida', 'esta_respondida', server_default=sa.text('0'))

    op.alter_column('preguntas_partida', 'es_correcta', server_default=None)
    op.alter_column(
        'preguntas_partida', 'es_correcta',
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using='es_correcta::integer',
    )
    op.alter_column('preguntas_partida', 'es_correcta', server_default=sa.text('0'))
    # ### end Alembic commands ###