"""crear_tablas_torneos_participantes_cruces

Revision ID: 50ca309bd94c
Revises: d7518665d6ec
Create Date: 2026-09-23 19:26:18.402382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ca309bd94c'
down_revision: Union[str, None] = 'd7518665d6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torneos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad_participantes', sa.Integer(), nullable=False),
    sa.Column('codigo_acceso', sa.String(length=10), nullable=False),
    sa.Column('contrasena_acceso', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('ESPERANDO_JUGADORES', 'EN_CURSO', 'FINALIZADO', name='estado_torneo_enum'), server_default='ESPERANDO_JUGADORES', nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torneos_codigo_acceso'), 'torneos', ['codigo_acceso'], unique=True)
    op.create_index(op.f('ix_torneos_creador_id'), 'torneos', ['creador_id'], unique=False)
    op.create_index(op.f('ix_torneos_id'), 'torneos', ['id'], unique=False)
    op.create_table('participantes_torneo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torneo_id', 'usuario_id', name='uq_participante_torneo_usuario')
    )
    op.create_index(op.f('ix_participantes_torneo_id'), 'participantes_torneo', ['id'], unique=False)
    op.create_index(op.f('ix_participantes_torneo_torneo_id'), 'participantes_torneo', ['torneo_id'], unique=False)
    op.create_index(op.f('ix_participantes_torneo_usuario_id'), 'participantes_torneo', ['usuario_id'], unique=False)
    op.create_table('cruces_torneo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('ronda', sa.Integer(), nullable=False),
    sa.Column('jugador_a_id', sa.Integer(), nullable=False),
    sa.Column('jugador_b_id', sa.Integer(), nullable=False),
    sa.Column('ganador_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'JUGADO', name='estado_cruce_enum'), server_default='PENDIENTE', nullable=False),
    sa.ForeignKeyConstraint(['ganador_id'], ['participantes_torneo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jugador_a_id'], ['participantes_torneo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jugador_b_id'], ['participantes_torneo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruces_torneo_ganador_id'), 'cruces_torneo', ['ganador_id'], unique=False)
    op.create_index(op.f('ix_cruces_torneo_id'), 'cruces_torneo', ['id'], unique=False)
    op.create_index(op.f('ix_cruces_torneo_jugador_a_id'), 'cruces_torneo', ['jugador_a_id'], unique=False)
    op.create_index(op.f('ix_cruces_torneo_jugador_b_id'), 'cruces_torneo', ['jugador_b_id'], unique=False)
    op.create_index(op.f('ix_cruces_torneo_torneo_id'), 'cruces_torneo', ['torneo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cruces_torneo_torneo_id'), table_name='cruces_torneo')
    op.drop_index(op.f('ix_cruces_torneo_jugador_b_id'), table_name='cruces_torneo')
    op.drop_index(op.f('ix_cruces_torneo_jugador_a_id'), table_name='cruces_torneo')
    op.drop_index(op.f('ix_cruces_torneo_id'), table_name='cruces_torneo')
    op.drop_index(op.f('ix_cruces_torneo_ganador_id'), table_name='cruces_torneo')
    op.drop_table('cruces_torneo')
    op.drop_index(op.f('ix_participantes_torneo_usuario_id'), table_name='participantes_torneo')
    op.drop_index(op.f('ix_participantes_torneo_torneo_id'), table_name='participantes_torneo')
    op.drop_index(op.f('ix_participantes_torneo_id'), table_name='participantes_torneo')
    op.drop_table('participantes_torneo')
    op.drop_index(op.f('ix_torneos_id'), table_name='torneos')
    op.drop_index(op.f('ix_torneos_creador_id'), table_name='torneos')
    op.drop_index(op.f('ix_torneos_codigo_acceso'), table_name='torneos')
    op.drop_table('torneos')
    sa.Enum(name='estado_cruce_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='estado_torneo_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

